#!/bin/sh

udhcpc -i eth0
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
ifconfig eth1 192.168.10.1 netmask 255.255.255.0
#route add -net 192.168.10.0 netmask 255.255.255.0 dev eth1
